// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xosayblhqeoimmudxnhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvc2F5YmxocWVvaW1tdWR4bmh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MzY2ODUsImV4cCI6MjA2MzMxMjY4NX0.tlBdtPcHUuWtPav5aZ93egCuDnUC0MYvZcqWGARBJCU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);